"""Add is_edit to events_details

Revision ID: 0a80f75aab87
Revises: 2bd8c788feca
Create Date: 2026-05-02 10:17:41.249401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a80f75aab87'
down_revision: Union[str, None] = '2bd8c788feca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_details', sa.Column('is_edit', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events_details', 'is_edit')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
