"""add_emitent_inn_to_events_details

Revision ID: 2bd8c788feca
Revises: 95222e84fe63
Create Date: 2026-04-18 14:11:29.107722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2bd8c788feca'
down_revision: Union[str, None] = '95222e84fe63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events_details', sa.Column('emitent_inn', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_events_details_emitent_inn'), 'events_details', ['emitent_inn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_details_emitent_inn'), table_name='events_details')
    op.drop_column('events_details', 'emitent_inn')
    # ### end Alembic commands ###
