"""create_events_details_table

Revision ID: 95222e84fe63
Revises: 021
Create Date: 2026-04-18 13:59:08.386745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95222e84fe63'
down_revision: Union[str, None] = '021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudo_guid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issue_registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('security_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publication_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pseudo_guid', 'event_date', name='uq_events_details_guid_date')
    )
    op.create_index(op.f('ix_events_details_event_date'), 'events_details', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_details_pseudo_guid'), 'events_details', ['pseudo_guid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_details_pseudo_guid'), table_name='events_details')
    op.drop_index(op.f('ix_events_details_event_date'), table_name='events_details')
    op.drop_table('events_details')
    # ### end Alembic commands ###
